version: "3.2"
services:
  powerdns:
    image: magichuihui/powerdns:v0.1
    volumes:
      - ./pdns.conf:/etc/pdns/pdns.conf
    ports:
      - 127.0.0.1:53:53/tcp
      - 127.0.0.1:53:53/udp
      - 8081:8081/tcp
    networks:
      - powerdns-net
    command: /usr/sbin/pdns_server --daemon=no --guardian=no --loglevel=9
    
networks:
  powerdns-net:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24
